name: NodeJS CI
on: 
  push:
    branches: [ main ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    services:
      mongodb:
        image: mongo:6.0.1
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      working-directory: ./backend
      run: npm install
    - name: Run All Node.js Tests
      working-directory: ./backend
      env:
        ENV: ${{ secrets.ENV }}
        DB_LOCAL_URI: ${{ secrets.DB_LOCAL_URI }}
      run: npm run test