name: NodeJS CI/CD
on: 
  push:
    branches: [ main ]
jobs:
  test:
    name: Test
    
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: ['6.0']
        platform: [ubuntu-latest]
    
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        mongodb-db: mydb
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      working-directory: ./backend
      run: npm install
    
    - name: Run All Node.js Tests
      working-directory: ./backend
      env:
        ENV: ${{ secrets.ENV }}
        DB_LOCAL_URI: ${{ secrets.DB_LOCAL_URI }}
      run: npm run test
  
  deploy:
    needs: [test]
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout the files
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: Generate deployment package
      run: zip -r deploy.zip * -x "**node_modules**"

    - name: Beanstalk Deploy for app
      uses: einaregilsson/beanstalk-deploy@v20
      working-directory: ./backend
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.AWS_APPLICATION_NAME }}
        environment_name: ${{ secrets.AWS_APPLICATION_ENV }}
        region: ap-southeast-1
        version_label: 1
        deployment_package: deploy.zip
